#ifndef CRAFTER2DLIB_GLOBAL_HPP
#define CRAFTER2DLIB_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(CRAFTER2DLIB_LIBRARY)
#  define CRAFTER2DLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CRAFTER2DLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CRAFTER2DLIB_GLOBAL_HPP
